### ISSUE TITLE
Live demo returns http status 500

### ISSUE THREAD

**Issue by janosh** [spences10/sveltekit-starter-blog#12]
Just to let you know that https://sveltekit-starter-blog.vercel.app is returning a status code 500 (Internal Server Error).

**Comment by spences10** [comment]
Hey @janosh, yeah I've broken it by adding authentication. I'll be fixing it soon™️

**Comment by spences10** [comment]
This should be fine now @janosh let me know if you still have issues accessing it

thanks

closing now
